[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Next.js output)
  publish = ".next"
  
  # Build timeout
  command_timeout_minutes = 15

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build optimizations
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Memory optimization for build process
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--include=dev"

# Essential plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Wallpaper videos caching - 30 days
[[headers]]
  for = "/wallpapers/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"
    Accept-Ranges = "bytes"

# API routes - no caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"