[build]
  # Build command with monitoring
  command = "npm run build:production"
  
  # Directory to publish (Next.js output)
  publish = ".next"
  
  # Build timeout
  command_timeout_minutes = 15

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build optimizations
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Enable build caching for faster deployments
  NPM_FLAGS = "--prefer-offline --no-audit"
  
  # Memory optimization for build process
  NODE_OPTIONS = "--max-old-space-size=4096"

# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Build caching for faster deployments
[build.cache]
  # Cache node_modules for faster installs
  node_modules = true
  
  # Cache Next.js build artifacts
  ".next/cache" = true
  
  # Cache package manager files
  "package-lock.json" = true
  "yarn.lock" = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers (complementing Next.js config)
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Static assets caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# API routes caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build plugins for optimization
[[plugins]]
  package = "netlify-plugin-lighthouse"
  
  [plugins.inputs.audits]
    performance = true
    accessibility = true
    best-practices = true
    seo = true
    pwa = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment-specific settings
[context.production]
  command = "npm run build:production"
  
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.deploy-preview]
  command = "npm run build:production"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.branch-deploy]
  command = "npm run build:production"

# Functions configuration (if needed for API routes)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"